export interface CreateCustomerInput {
    /**
     * Address city.
     */
    address_city: string;
    /**
     * Address line one.
     */
    address_line_one: string;
    /**
     * Address line two.
     */
    address_line_two?: string;
    /**
     * Address state.
     */
    address_state: string;
    /**
     * Five digit zipcode or nine digit 'ZIP+4'.
     */
    address_zip: string;
    /**
     * An array of existing accounts to which this Customer should be assigned. If left empty,
     * the customer will not be assigned to any accounts, and can be later assigned to an
     * account via the [Update an existing
     * customer](https://docs.canopyservicing.com/#operation-put-accounts-parameter) route.
     * Customers only become meaningful agents in Canopy's servicing system once they are
     * assigned to accounts.
     */
    assign_to_accounts?: AssignToAccount[];
    business_details?:   BusinessDetails;
    /**
     * Customer's date of birth in ISO 8601 format.
     */
    date_of_birth: string;
    /**
     * The Customer's email address.
     */
    email: string;
    /**
     * Customer's first name.
     */
    name_first: string;
    /**
     * Customer's last name.
     */
    name_last: string;
    /**
     * Customer's middle name.
     */
    name_middle?: string;
    /**
     * Prefix to the customer's name.
     */
    name_prefix?: string;
    /**
     * Suffix to the customer's name.
     */
    name_suffix?: string;
    /**
     * Customer's phone number in E.164 format.
     */
    phone_number: string;
    /**
     * Social security number of the customer.
     */
    ssn: string;
}

export interface AssignToAccount {
    /**
     * This is generated by Canopy. A unique ID for the account.
     */
    account_id?: string;
    /**
     * A unique number for the customer on the account. For instance, a credit card number. If
     * none is provided, a Canopy-generated ID can be used.
     */
    customer_account_external_id?:             string;
    customer_account_issuer_processor_config?: CustomerAccountIssuerProcessorConfig;
    /**
     * The role of the customer for the account.
     */
    customer_account_role?: CustomerAccountRole;
}

export interface CustomerAccountIssuerProcessorConfig {
    lithic?: Lithic;
}

export interface Lithic {
    /**
     * Friendly name to identify the card.
     */
    memo?: string;
    /**
     * The state of the new card.
     */
    state?: State;
    /**
     * The type of card created by Lithic.
     */
    type?: Type;
}

/**
 * The state of the new card.
 */
export type State = 
    "OPEN" | 
    "PAUSED";

/**
 * The type of card created by Lithic.
 */
export type Type = 
    "MERCHANT_LOCKED" | 
    "SINGLE_USE" | 
    "UNLOCKED";

/**
 * The role of the customer for the account.
 */
export type CustomerAccountRole = 
    "CARDHOLDER" | 
    "PRIMARY" | 
    "SECONDARY";

export interface BusinessDetails {
    /**
     * EIN of the business.
     */
    business_ein: string;
    /**
     * The legal name of the Business.
     */
    business_legal_name: string;
    /**
     * The DBA name of the Business.
     */
    doing_business_as: string;
}
