type CreateCustomerInput struct {
	AddressCity      string            `json:"address_city"`                // Address city.
	AddressLineOne   string            `json:"address_line_one"`            // Address line one.
	AddressLineTwo   *string           `json:"address_line_two,omitempty"`  // Address line two.
	AddressState     string            `json:"address_state"`               // Address state.
	AddressZip       string            `json:"address_zip"`                 // Five digit zipcode or nine digit 'ZIP+4'.
	AssignToAccounts []AssignToAccount `json:"assign_to_accounts,omitempty"`// An array of existing accounts to which this Customer should be assigned. If left empty,; the customer will not be assigned to any accounts, and can be later assigned to an; account via the [Update an existing; customer](https://docs.canopyservicing.com/#operation-put-accounts-parameter) route.; Customers only become meaningful agents in Canopy's servicing system once they are; assigned to accounts.
	BusinessDetails  *BusinessDetails  `json:"business_details,omitempty"`  
	DateOfBirth      string            `json:"date_of_birth"`               // Customer's date of birth in ISO 8601 format.
	Email            string            `json:"email"`                       // The Customer's email address.
	NameFirst        string            `json:"name_first"`                  // Customer's first name.
	NameLast         string            `json:"name_last"`                   // Customer's last name.
	NameMiddle       *string           `json:"name_middle,omitempty"`       // Customer's middle name.
	NamePrefix       *string           `json:"name_prefix,omitempty"`       // Prefix to the customer's name.
	NameSuffix       *string           `json:"name_suffix,omitempty"`       // Suffix to the customer's name.
	PhoneNumber      string            `json:"phone_number"`                // Customer's phone number in E.164 format.
	Ssn              string            `json:"ssn"`                         // Social security number of the customer.
}

type AssignToAccount struct {
	AccountID                            *string                               `json:"account_id,omitempty"`                              // This is generated by Canopy. A unique ID for the account.
	CustomerAccountExternalID            *string                               `json:"customer_account_external_id,omitempty"`            // A unique number for the customer on the account. For instance, a credit card number. If; none is provided, a Canopy-generated ID can be used.
	CustomerAccountIssuerProcessorConfig *CustomerAccountIssuerProcessorConfig `json:"customer_account_issuer_processor_config,omitempty"`
	CustomerAccountRole                  *CustomerAccountRole                  `json:"customer_account_role,omitempty"`                   // The role of the customer for the account.
}

type CustomerAccountIssuerProcessorConfig struct {
	Lithic *Lithic `json:"lithic,omitempty"`
}

type Lithic struct {
	CardProgramToken *string `json:"card_program_token,omitempty"`// Token belonging to the card program under which to create the card.
	Memo             *string `json:"memo,omitempty"`              // Friendly name to identify the card.
	State            *State  `json:"state,omitempty"`             // The state of the new card.
	Type             *Type   `json:"type,omitempty"`              // The type of card created by Lithic.
}

type BusinessDetails struct {
	BusinessEin       string `json:"business_ein"`       // EIN of the business.
	BusinessLegalName string `json:"business_legal_name"`// The legal name of the Business.
	DoingBusinessAs   string `json:"doing_business_as"`  // The DBA name of the Business.
}

// The state of the new card.
type State string
const (
	Open State = "OPEN"
	Paused State = "PAUSED"
)

// The type of card created by Lithic.
type Type string
const (
	MerchantLocked Type = "MERCHANT_LOCKED"
	SingleUse Type = "SINGLE_USE"
	Unlocked Type = "UNLOCKED"
)

// The role of the customer for the account.
type CustomerAccountRole string
const (
	Cardholder CustomerAccountRole = "CARDHOLDER"
	Primary CustomerAccountRole = "PRIMARY"
	Secondary CustomerAccountRole = "SECONDARY"
)
