name: Deploy documentation to internal docs hub

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out latest code
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: cache
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install node_modules
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn

      - name: Bundle into one file
        run: yarn bundle

      - name: Validate
        run: yarn validate

      - name: Deploy to internal documentation
        uses: bump-sh/github-action@0.1
        with:
          id: ${{ secrets.BUMP_DOC_ID_INTERNAL }}
          token: ${{ secrets.BUMP_TOKEN_INTERNAL }}
          file: dist/consolidated.json
