name: Deploy production docs

on:
  push:
    branches:
      - production

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out latest code
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: cache
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install node_modules
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn

      - name: Bundle and validate OpenAPI spec
        run: yarn build

      - name: Deploy to docs.canopyservicing.com
        uses: bump-sh/github-action@0.2
        with:
          doc: ${{ secrets.BUMP_DOC_ID_LIVE }}
          token: ${{ secrets.BUMP_TOKEN_LIVE }}
          file: dist/consolidated.json
